services:
  postgresql:
    depends_on:
      bootstrap:
        condition: service_completed_successfully
    image: postgres:17-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - "${DCM_CONFIG_DIR}/config.env"
      # - "${DCM_CONFIG_DIR}/postgresql/postgresql.env"
    volumes:
      - ${DCM_VOLUMES_DIR}/DCMBase/Postgres/data:/var/lib/postgresql/data:z
      - ./init:/docker-entrypoint-initdb.d:z
    ports:
      - "5432:5432"
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
